### ISSUE TITLE
Unable to bundle install

### ISSUE THREAD

**Issue by matsp10** [alown/rosc#1]
Hi ! 

Firstable, thank you very much for that, It seems to be exactly what I've looked for and since a few people seem interested in that, I wanted to let you know that It would be very useful to me. 👍 

So. You have to know that I'm not very good when It comes to command-line stuff, I'm no IT expert at all, I just really want your program to run on my machine !

The problem I'm having is the following : 

I'm on OSx 10.9.5, running ruby 2.5.1p57 and bundler 1.16.2.
When I try to bundle install, I get errors (I'll copy them, I can send you the full paste of those If needed) and the main one is that eventmachine 1.0.3 doesn't want to get installed on my mac.
So I tried to get the latest version of it and then bundle install, it doesn't work.
I tried then to get the 1.0.4 (with very little hope) and It still didn't work, so I guess I really need to have the 1.0.3 and I really don't get how to.

So here is how my terminal responds to the Bundle Install (what seems to be main errors only) : 
```
Fetching gem metadata from https://rubygems.org/..............
Resolving dependencies...
Using bundler 1.16.2
Fetching eventmachine 1.0.3
Installing eventmachine 1.0.3 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

```
and later 

```
40 warnings and 3 errors generated.
make: *** [em.o] Error 1

make failed, exit code 2

Gem files will remain installed in
~/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/eventmachine-1.0.3
for inspection.
Results logged to
~/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/extensions/x86_64-darwin-13/2.5.0-static/eventmachine-1.0.3/gem_make.out

An error occurred while installing eventmachine (1.0.3), and Bundler
cannot continue.
Make sure that ’gem install eventmachine -v '1.0.3' --source
'https://rubygems.org/'’ succeeds before bundling.

In Gemfile:
  ruby-osc was resolved to 0.31.0, which depends on
    eventmachine
```

If you have any idea of to resolve this, I would greatly appreciate It ! 

Have a good day.

**Comment by matsp10** [comment]
P.S. : Don't know if that was clear : I was able to install the most recent eventmachine AND the 1.0.4 and what didn't work was not the installation of them of the bundle install after that, obviously. 
I also tried before Bundle Install to just `gem install eventmachine -v 1.0.3` which led to the same king of errors.
Thanks again !

**Comment by alown** [comment]
Hi Matsp10,

Thank you for the bug report, it was incredibily thorough (though there is certainly no harm attaching the full log file in future if you run into anything else).

As I hadn't particularly touched this codebase in the last 4 years, it was not really a surprise that it no longer worked out of the box! It looks like eventmachine no longer 1.0.3 no longer compiles on modern GCC/Clang with modern rubies.

I have bumped the Gemfile.lock, as well as tidied up a few other things. A quick test here shows it all working as well as it ever did.

Feel free to open new issues if you run into any other problems (or even better send some pull requests to improve it!)

Hope you find it useful.
